### ISSUE TITLE
Prevent invalid SSH keys from being submitted to gitolite.

### ISSUE THREAD

**Issue by michaeldejong** [devhub-tud/git-server#33]
We've had issues with people submitting invalid SSH keys, or SSH keys with exotic algorithms which gitolite doesn't seem to understand.

We should check the validity of SSH keys in some way. I've looked for various implementations of SSH key checkers in Java, but none of them seemed to work. To detect invalid SSH keys on the server (once the damage was already done) I used the following command:

`ssh-keygen -lf <filename>`

which either produces a line like:
`2048 59:78:49:21:35:ea:ba:ba:f4:3c:b8:d8:67:bf:72:1e  <netID> (RSA)`

or not when it's invalid. Perhaps we can use this to validate SSH keys before submitting them to gitolite.

**Comment by michaeldejong** [comment]
This key was wrongfully accepted:

```
ssh-rsa 2048 b2:08:34:36:20:65:a6:64:9c:f5:cc:10:08:68:6d:8f
```

**Comment by JWGmeligMeyling** [comment]
This key doesn't get through the new preconditions in the new Gitolite manager. Did we do `mvn install` for the new Gitolite on deployment?
